# ====== Name and seed ======
name: horm_t1x_hip_pairv2_512_mae
seed: 42

# ====== Directories ======
work_dir: .
log_dir: logs/horm_t1x_hip_pairv2_512_mae
model_dir: null
checkpoints_dir: checkpoints/horm_t1x_hip_pairv2_512_mae
results_dir: results/horm_t1x_hip_pairv2_512_mae
downloads_dir: null

# ====== Device and logging ======
device: cuda
default_dtype: float32 # bfloat16 float32
distributed: false
launcher: slurm
log_level: INFO
plot: true
error_table: TotalMAE # TotalMAEHessian
save_all_checkpoints: true

# ====== Model ======
model: MACE
r_max: 7.0
num_radial_basis: 16
max_ell: 3
correlation: 3
num_interactions: 2
MLP_irreps: "16x0e"
radial_MLP: "[64, 64, 64]"
hidden_irreps: "512x0e + 512x1e + 512x1o + 512x2e"
edge_irreps: null
max_L: null
avg_num_neighbors: 12.876944541931152
compute_avg_num_neighbors: false
compute_forces: true

# ====== HIP / Hessian prediction ======
hip: true
hessian_head_type: pair_v2
hessian_feature_dim: 512
hessian_fully_connected: true
num_interactions_hessian: 0
hessian_hidden_irreps: "512x0e + 512x1e + 512x1o + 512x2e"


# ====== Dataset ======
train_file: ./data/ts1x/ts1x_hess_train
valid_file: ./data/ts1x/ts1x-val
# valid_fraction: 0.1 # only used when no explicit validation file is given
max_valid_samples: 1000
samples_per_epoch: 20000 # stop the epoch early after this many samples
test_file: null
test_dir: null
num_workers: 4
pin_memory: true
atomic_numbers: "[1, 6, 7, 8, 9]"
mean: -611.9894409179688
std: 0.38076332211494446
statistics_file: null
les_arguments: null
# https://gitlab.com/matschreiner/Transition1x/-/blob/main/transition1x/dataloader.py
E0s: "{1: -13.62222753701504, 6: -1029.4130839658328, 7: -1484.8710358098756, 8: -2041.8396277138045, 9: -2712.8213146878606}"

# ====== Keys ======
energy_key: energy
forces_key: forces
hessian_key: hessian # for HIP

# ====== Loss and optimization ======
loss: maeenergyforceshessian
hessian_weight: 25.0
forces_weight: 10.0
energy_weight: 1.0
virials_weight: 0.0
optimizer: adamw
beta: 0.9
batch_size: 64
valid_batch_size: 64
lr: 0.08
weight_decay: 0 # 5e-7
# amsgrad: true
scheduler: CosineAnnealingLR
warmup_epochs: 150
min_lr: 0.00001
swa: false # stochastic weight averaging
ema: false # exponential moving average
ema_decay: 0.999
max_num_epochs: 1500
patience: 2048
eval_interval: 10
final_eval: false

# ====== Acceleration options ======
enable_cueq: false
only_cueq: true
enable_oeq: false

# ====== Weights and Biases ======
wandb: true
wandb_dir: null
wandb_project: hip-mace
wandb_entity: ""
wandb_name: horm_t1x_hip_pairv2_512_mae
wandb_log_hypers: null
